# Copyright (C) 2018-2020 Virto Solutions. All Rights Reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
version: '3.7'

services:

  vc-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: v!rto_Labs!
      PGDATA: /data/postgres
    volumes:
       - ./init-db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
       - db-volume:/data/postgres
    networks:
      - virto
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  vc-platform-web:
    image: virtocommerce/platform:${DOCKER_TAG:-latest}
    ports:
      - "${DOCKER_PLATFORM_PORT:-8090}:80"
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+
      - VirtoCommerce:AllowInsecureHttp=true
      - DatabaseProvider=PostgreSql
      - ConnectionStrings:VirtoCommerce=User ID=postgres;Password=v!rto_Labs!;Host=vc-db;Port=5432;Database=vc_lab;
      - Assets:FileSystem:PublicUrl=http://localhost:${DOCKER_PLATFORM_PORT:-8090}/assets/
      - Content:FileSystem:PublicUrl=http://localhost:${DOCKER_PLATFORM_PORT:-8090}/cms-content/
      - Search:Provider=Lucene
    depends_on:
      vc-db:
        condition: service_healthy

    volumes:
      - cms-content-volume:/opt/virtocommerce/platform/wwwroot/cms-content
      - modules-volume:/opt/virtocommerce/platform/modules
    networks:
      - virto

  vc-storefront-web:
    image: virtocommerce/storefront:${DOCKER_TAG:-latest}
    ports:
      - "${DOCKER_STOREFRONT_PORT:-8081}:80"
    environment:
      - VirtoCommerce:Endpoint:Url=http://vc-platform-web
      - VirtoCommerce:Endpoint:UserName=admin
      - VirtoCommerce:Endpoint:Password=store
      - ASPNETCORE_ENVIRONMENT=Development 
    depends_on:
      - vc-platform-web
    volumes:
      - cms-content-volume:/opt/virtocommerce/storefront/wwwroot/cms-content
    networks:
      - virto

volumes:
  cms-content-volume:
    name: cms-content-data
  modules-volume:
    name: modules-data
  db-volume:
    name: db-data

networks:
  virto:
    external: true